version: 2.1

parameters:
  workflow:
    type: enum
    default: build
    description: Workflow targets.
    enum: [build, publish]

executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:buster
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile --target aws-cli -t "aws-cli:latest" .
            docker build -f Dockerfile --target aws-cli-serverless -t "aws-cli:latest-serverless" .
      - run:
          name: Check kubectl
          command: docker run -it aws-cli:latest "which" "kubectl"
      - run:
          name: Check aws
          command: docker run -it aws-cli:latest "aws" "--version"
      - run:
          name: Check all versions
          command: |
            echo "[kubectl] "$(docker run -it aws-cli:latest "kubectl"  "version" | head -n 1)
            echo "[aws] "$(docker run -it aws-cli:latest "aws"      "--version" | head -n 1)
            echo "[pip3] "$(docker run -it aws-cli:latest "pip3"     "--version" | head -n 1)
            echo "[python3] "$(docker run -it aws-cli:latest "python3"  "--version" | head -n 1)
            echo "[curl] "$(docker run -it aws-cli:latest "curl"     "--version" | head -n 1)
            echo "[git] "$(docker run -it aws-cli:latest "git"      "--version" | head -n 1)
            echo "[docker] "$(docker run -it aws-cli:latest "docker"   "--version" | head -n 1)
            echo "[jq] "$(docker run -it aws-cli:latest "jq"       "--version" | head -n 1)
            echo "[ytt] "$(docker run -it aws-cli:latest "ytt"      "--version" | head -n 1)

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image and serverless flavor
          command: |
            docker build -f Dockerfile --target aws-cli -t "deryker/aws-cli-plus:latest" -t "deryker/aws-cli-plus:${CIRCLE_TAG}" .
            docker build -f Dockerfile --target aws-cli-serverless -t "deryker/aws-cli-plus:latest-serverless" -t "deryker/aws-cli:${CIRCLE_TAG}-serverless" .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push deryker/aws-cli-plus:latest
            docker push deryker/aws-cli-plus:${CIRCLE_TAG}
            docker push deryker/aws-cli-plus:latest-serverless
            docker push deryker/aws-cli-plus:${CIRCLE_TAG}-serverless

workflows:
  build-test:
    when: { equal: [build, << pipeline.parameters.workflow >>] }
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    when: { equal: [publish, << pipeline.parameters.workflow >>] }
    jobs:
      - publish-latest-docker-image:
          context: dockerAwsCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
